receivers:
  otlp:
    protocols:
      # Need to set endpoint since v0.104.0 - https://opentelemetry.io/blog/2024/hardening-the-collector-one/
      # TODO: Ought to set specific IP / Host name rather than `0.0.0.0`
      grpc:
        endpoint: 0.0.0.0:${PORT_GRPC}
      http:
        endpoint: 0.0.0.0:${PORT_HTTP}

exporters:
  otlp/aspire:
    endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}
    tls:
      # For GRPC
      insecure: true
      # For HTTPS ignoring certs
      insecure_skip_verify: true
    headers:
      x-otlp-api-key: ${env:ASPIRE_API_KEY}


# Add a fake annotation so we can be sure telemetry came through the collector
processors:
  attributes/annotate-from-collector:
    actions:
      - key: from-collector
        value: true
        action: insert

# Forward all signals from otlp reciever to otlp/aspire, whilst applying the fake annotation
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: ['attributes/annotate-from-collector']
      exporters: [otlp/aspire]
    metrics:
      receivers: [otlp]
      processors: ['attributes/annotate-from-collector']
      exporters: [otlp/aspire]
    logs:
      receivers: [otlp]
      processors: ['attributes/annotate-from-collector']
      exporters: [otlp/aspire]