apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  AZURE_OPENAI_API_KEY: {{.Env.AZURE_OPENAI_API_KEY}}
  AZURE_OPENAI_ENDPOINT: {{.Env.AZURE_OPENAI_ENDPOINT}}
  AZURE_OPENAI_CHAT_DEPLOYMENT_NAME: {{.Env.AZURE_OPENAI_CHAT_DEPLOYMENT_NAME}}
  AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME: {{.Env.AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME}}
  AZURE_OPENAI_API_VERSION: {{.Env.AZURE_OPENAI_API_VERSION}}