apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: {{.Env.SERVICE_API_IMAGE_NAME}}
          ports:
            - containerPort: 8000
          env:            
            - name: AZURE_OPENAI_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: AZURE_OPENAI_API_KEY
                  optional: false
            - name: AZURE_OPENAI_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: AZURE_OPENAI_ENDPOINT
                  optional: false
            - name: AZURE_OPENAI_CHAT_DEPLOYMENT_NAME 
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: AZURE_OPENAI_CHAT_DEPLOYMENT_NAME
                  optional: false
            - name: AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME
                  optional: false
             - name: AZURE_OPENAI_API_VERSION
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: AZURE_OPENAI_API_VERSION
                  optional: false
            